### ISSUE TITLE
Snakemake profile for slurm

### ISSUE THREAD

**Issue by sarah872** [pyani-plus/pyani-plus#370]
Hi,

I'm getting the following error:

```
pyani-plus anim --create-db --database genomes.db --executor slurm --name only_genomes --temp temp1 genomes
[06/10/25 18:01:17] INFO     Logging to 'pyani-plus.log'
Indexing FASTAs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:06 38/38
[06/10/25 18:01:25] INFO     ANIm run setup with 38 genomes in database
[06/10/25 18:01:25] INFO     Database already has 0 of 38²=1444 ANIm comparisons, 1444 needed
[06/10/25 18:01:25] INFO     No per-genome preparation required for ANIm

Error: maximum number of parallel jobs/used nodes has to be specified for remote execution (use --jobs N with N being a number >= 1)

[06/10/25 18:01:37] CRITICAL Snakemake workflow failed
```
I found a similar issue here, but I could not follow how to change the Snakemake profile. Could you please give me guidance?

**Comment by peterjc** [comment]
I just typed and lost a longer answer - but this needs to be added to https://pyani-plus.github.io/pyani-plus-docs/

Toy example config for [Archie West](https://www.archie-west.ac.uk/) SLURM cluster using modules, activating conda, and then activating a conda environment: https://github.com/pyani-plus/pyani-plus/pull/149#issuecomment-2435619962w

Toy example config for [Crop Diversity](https://cropdiversity.ac.uk) SLURM cluster using conda automatically (and pyani-plus in the base environment): https://github.com/pyani-plus/pyani-plus/pull/149#issuecomment-2436203966

With this approach your ``config.yaml`` would have a line like ``jobs: 400`` (
r upper limit on Archie West) and ``cores: 1`` (each job is single threaded).

Real example, my ``snakemake-profile-crop-diversity/config.yaml`` where I need nothing extra to have all the binaries available:

```yaml
executor: slurm
jobs: 1000
cores: 1

default-resources:
    slurm_partition: short
    slurm_account: cropdiv-acc
    runtime: 100

# When left out the account, got this message from snakemake (in purple):
#   No SLURM account given, trying to guess.
#
# When left out time limits, got this message from snakemake (in purple):
#  No wall time information given. This might or might not work
#  on your cluster. If not, specify the resource runtime in your
#  rule or as a reasonable default via --default-resources.
```
